services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      shared:
    environment:
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3001,http://localhost:3000

networks:
  shared:
    driver: bridge
    enable_ipv4: true
    enable_ipv6: false
